[package]
name = "confy-jschema-configs"
version = "0.1.0"
edition = "2021"
[build-dependencies]
typify = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
syn = { workspace = true }
prettyplease = { workspace = true }

[dependencies]
confique = { version = "0.1", features = ["toml"], optional = true }
telety = { workspace = true, optional = true }
serde_json = { workspace = true }
serde = { workspace = true }
regress = { workspace = true }
thiserror = { workspace = true }
cargo_toml = { workspace = true }
confy-macros = { path = "../macros" }
document-features = { workspace = true }

[features]
default = ["confique", "modules"]
## Enable [pyproject], [deno], [package] and [cargo] module
modules = ["pyproject", "deno", "package", "cargo"]
## Enable [cargo] module
cargo = []
## Enable [package] module
package = []
## Enable [deno] module
deno = []
## Enable [pyproject] module
pyproject = []
## Enable derive [Config](confique::Config) for [cargo](cargo::ConfigRoot), [deno](deno::ConfigRoot), [pyproject](pyproject::ConfigRoot), [package](package::ConfigRoot) `ConfigRoot`
confique = ["dep:confique"]
## Enable [telety] for [cargo](cargo::ConfigRoot), [deno](deno::ConfigRoot), [pyproject](pyproject::ConfigRoot), [package](package::ConfigRoot) `ConfigRoot`
telety = ["dep:telety"]
