[package]
name = "confy-jschema-configs"
version = "0.1.0"
edition = "2021"
[build-dependencies]
typify = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
syn = { workspace = true }
prettyplease = { workspace = true }

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true }
regress = { workspace = true }
thiserror = { workspace = true }
confique = { workspace = true, features = ["toml"] }
