[package]
name = "confy-project-meta"
version = "0.1.0"
edition = "2021"
[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
confique = { workspace = true, features = ["toml"] }
[dev-dependencies]
insta = { workspace = true, features = ["yaml", "redactions"] }
